package br.com.ibm.cadeiabatch.enums;

public enum CategoriaEnum {

	SAP_BW
	,SAP_FI
	,SAP_CO
	,SAP_MM_Financeiro
	,SAP_MM_Suprimentos
	,SAP_MM_Tributos
	,SAP_WM
	,SAP_SD
	,SAP_DS
	,SAP_PI
	,SAP_SI
	,SAP_BPC
	,SAP_DBA
	,SAP_FSCD
	,SAP_ABAP
	,SAP_BASIS
	,SAP_WORKFLOW
	,_4GL_Comissões
	,_4GL_Contabilidade
	,_4GL_Financeiro
	,JAVA_Financeiro
	,JAVA_Comissões
	,JAVA_Contabilidade
	,AMS_Automação_BAW
	,AMS_Automação_RPA
	,AMS_Canais_Digitais_AGV_Legado
	,AMS_Canais_Digitais_Front_AGV
	,AMS_Canais_Digitais_Front_APP
	,AMS_Canais_Digitais_Backend
	,AMS_Canais_Digitais_Totem
	,AMS_Cognitivo_Ura
	,AMS_Cognitivo_Infra
	,AMS_Cognitivo_monitoração
	,AMS_Suporte
	,DEV_Automação_BAW
	,DEV_Automação_RPA
	,DEV_Canais_Digitais_AGV_Legado
	,DEV_Canais_Digitais_Front_AGV
	,DEV_Canais_Digitais_Front_APP
	,DEV_Canais_Digitais_Backend
	,DEV_Canais_Digitais_Totem
	,DEV_Cognitivo_Ura
	,DEV_Cognitivo_Infra
	,SAP_MM
	,SAP_FIORI
}
